name: pydata2020-mpf
channels:
  - defaults
dependencies:
  - pip:
    - jupyter==1.0.0
    - jupyterlab==2.1.1
    - matrixprofile<2.0.0
    - pandas<1.1.0
    - hdbscan<0.9.0>=0.8.18
    - ipython
    - sktime
